export const MAX_FILE_SIZE_TO_UPLOAD_AS_FILE = 5 * 1024 * 1024;

export const CHUNK_SIZE = 3 * 1024 * 1024;
export const MAX_FILE_SIZE = 300 * 1024 * 1024;

export enum UPLOADING_STATUS {
    NOT_PROGRESS = "NOT_PROGRESS",
    IN_PROGRESS = "IN_PROGRESS",
    PREPARING_ARCHIVE = "PREPARING_ARCHIVE"
}
